"""Turn the measured JSONL into the tables the README quotes.

Everything the README states as a number comes out of here, so a re-run
regenerates the claims rather than leaving them to drift.

  python scripts/summarize.py > docs/RESULTS.md
"""

import collections
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
RES = ROOT / "results"


def load(name):
    out = []
    p = RES / name
    if not p.exists():
        return out
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith("{"):
            out.append(json.loads(line))
    return out


def kernels(rows):
    return [r for r in rows if "kernel" in r and "gbps" in r and "max_abs_err" in r]


LABEL = {
    "q8_v0_naive":    ("q8_0", "ggml AoS", "thread per row",  "global"),
    "q8_v1_warp":     ("q8_0", "ggml AoS", "warp per row",    "global"),
    "q8_v2_smem_x":   ("q8_0", "ggml AoS", "warp per row",    "shared"),
    "q8_v3_soa_vec":  ("q8_0", "SoA 16 B", "warp per row",    "global"),
    "q8_v4_split2":   ("q8_0", "SoA 16 B", "2 warps per row", "global"),
    "q8_v4_split4":   ("q8_0", "SoA 16 B", "4 warps per row", "global"),
    "q8_v5_soa_smem": ("q8_0", "SoA 16 B", "warp per row",    "shared"),
    "q4_v0_naive":    ("q4_0", "ggml AoS", "thread per row",  "global"),
    "q4_v1_warp":     ("q4_0", "ggml AoS", "warp per row",    "global"),
    "q4_v2_smem_x":   ("q4_0", "ggml AoS", "warp per row",    "shared"),
    "q4_v3_soa_vec":  ("q4_0", "SoA 16 B", "warp per row",    "global"),
    "q4_v5_soa_smem": ("q4_0", "SoA 16 B", "warp per row",    "shared"),
}


def main():
    ceiling = load("ceiling_rtx3050.jsonl")
    dev = next((r for r in ceiling if "device" in r), {})
    stream = next((r for r in ceiling if r.get("kernel") == "stream_read"), None)
    d2d = next((r for r in ceiling if r.get("kernel") == "memcpy_d2d"), None)
    roof = stream["gbps_median"] if stream else None

    print("# Measured results\n")
    print("Generated by `scripts/summarize.py` from the JSONL in `results/`. "
          "Every row was measured on the device named below.\n")
    if dev:
        print(f"**Device.** {dev['device']}, {dev['cc']}, {dev['sms']} SMs, "
              f"L2 {dev['l2_bytes'] / 1024:.0f} KiB, {dev['bus_bits']}-bit bus, "
              f"memory clock {dev['mem_clock_khz'] / 1e6:.3f} GHz.\n")

    print("## 1. The ceiling\n")
    print("| measurement | GB/s | note |")
    print("|---|---|---|")
    if dev:
        print(f"| device-reported peak | {dev['datasheet_gbps_x2']:.1f} | "
              f"{dev['mem_clock_khz'] / 1e6:.3f} GHz x 2 x {dev['bus_bits']} bit / 8 |")
    if stream:
        print(f"| streaming read, measured | {stream['gbps_median']:.1f} | "
              f"512 MiB, int4 loads, median of 50 |")
    if d2d:
        print(f"| device-to-device copy | {d2d['gbps_median']:.1f} | read plus write |")
    tri = load("triton_rtx3050.jsonl")
    fp16 = next((r for r in tri if r.get("kernel") == "torch_fp16_mv"), None)
    if fp16 and roof:
        print(f"| cuBLAS fp16 matvec | {fp16['gbps']:.1f} | "
              f"{100 * fp16['gbps'] / roof:.1f}% of the streaming read |")
    print()
    if stream and dev:
        print(f"The streaming read reaches "
              f"{100 * stream['gbps_median'] / dev['datasheet_gbps_x2']:.1f}% of the "
              f"device-reported peak, and an unquantized cuBLAS matvec of the same "
              f"shape reaches {100 * fp16['gbps'] / roof:.1f}% of the streaming read. "
              f"Two independent paths agree on where the roof is.\n")

    for tag, fname in [("4096 x 4096", "ladder_4096x4096_rtx3050.jsonl"),
                       ("11008 x 4096", "ladder_11008x4096_rtx3050.jsonl")]:
        rows = kernels(load(fname))
        if not rows:
            continue
        print(f"## 2. The ladder, {tag}\n")
        print("| kernel | format | weight layout | rows | x lives in | ms (median) | "
              "GB/s | % of roof | max rel err |")
        print("|---|---|---|---|---|---|---|---|---|")
        for r in rows:
            fmt, lay, sched, xloc = LABEL.get(r["kernel"], ("?", "?", "?", "?"))
            pct = f"{100 * r['gbps'] / roof:.1f}%" if roof else "-"
            print(f"| `{r['kernel']}` | {fmt} | {lay} | {sched} | {xloc} | "
                  f"{r['ms_median']:.4f} | {r['gbps']:.1f} | {pct} | "
                  f"{r['max_rel_err']:.2g} |")
        print()

        # the factorial read
        g = {r["kernel"]: r for r in rows}
        if all(k in g for k in ("q8_v1_warp", "q8_v2_smem_x", "q8_v3_soa_vec", "q8_v5_soa_smem")):
            base = g["q8_v1_warp"]["gbps"]
            print("Factorial decomposition, q8_0, against the warp-per-row AoS baseline:\n")
            print("| change | GB/s | speedup |")
            print("|---|---|---|")
            print(f"| baseline (AoS, x in global) | {base:.1f} | 1.00x |")
            print(f"| layout only (SoA) | {g['q8_v3_soa_vec']['gbps']:.1f} | "
                  f"{g['q8_v3_soa_vec']['gbps'] / base:.2f}x |")
            print(f"| x placement only (shared) | {g['q8_v2_smem_x']['gbps']:.1f} | "
                  f"{g['q8_v2_smem_x']['gbps'] / base:.2f}x |")
            print(f"| both | {g['q8_v5_soa_smem']['gbps']:.1f} | "
                  f"{g['q8_v5_soa_smem']['gbps'] / base:.2f}x |")
            prod = (g["q8_v3_soa_vec"]["gbps"] / base) * (g["q8_v2_smem_x"]["gbps"] / base)
            both = g["q8_v5_soa_smem"]["gbps"] / base
            print(f"\nThe two effects multiply to {prod:.2f}x in isolation but deliver "
                  f"{both:.2f}x together, so they are not independent: both were "
                  f"relieving the same stall.\n")
        if "q8_v5_soa_smem" in g and "q4_v5_soa_smem" in g:
            a, b = g["q8_v5_soa_smem"], g["q4_v5_soa_smem"]
            print(f"**Format.** q4_0 moves "
                  f"{100 * (1 - b['weight_bytes'] / a['weight_bytes']):.0f}% fewer weight "
                  f"bytes than q8_0 and takes {b['ms_median'] / a['ms_median']:.2f}x "
                  f"as long ({b['ms_median']:.4f} ms against {a['ms_median']:.4f} ms).\n")

    # sweep
    sw = kernels(load("sweep_rtx3050.jsonl"))
    if sw:
        by = collections.defaultdict(dict)
        for r in sw:
            by[r["kernel"]][r["K"]] = r
        Ks = sorted({r["K"] for r in sw})
        print("## 3. Does it hold across shapes\n")
        print("Achieved GB/s at M = 4096.\n")
        print("| kernel | " + " | ".join(f"K={k}" for k in Ks) + " |")
        print("|---" * (len(Ks) + 1) + "|")
        for k in LABEL:
            if k in by:
                print(f"| `{k}` | " + " | ".join(
                    f"{by[k][x]['gbps']:.1f}" if x in by[k] else "-" for x in Ks) + " |")
        print()
        if "q8_v5_soa_smem" in by and "q4_v5_soa_smem" in by:
            print("| | " + " | ".join(f"K={k}" for k in Ks) + " |")
            print("|---" * (len(Ks) + 1) + "|")
            print("| q4_0 time / q8_0 time, best variant | " + " | ".join(
                f"{by['q4_v5_soa_smem'][x]['ms_median'] / by['q8_v5_soa_smem'][x]['ms_median']:.3f}"
                if x in by["q4_v5_soa_smem"] and x in by["q8_v5_soa_smem"] else "-"
                for x in Ks) + " |")
            print("\nThe 4-bit format is slower than the 8-bit one at every shape "
                  "measured, not at one convenient point.\n")

    # triton
    if tri:
        print("## 4. Triton against CUDA\n")
        lad = {r["kernel"]: r for r in kernels(load("ladder_11008x4096_rtx3050.jsonl"))}
        print("| implementation | format | ms (median) | GB/s | % of roof |")
        print("|---|---|---|---|---|")
        for r in tri:
            if r.get("kernel", "").startswith("triton") or r.get("kernel") == "torch_fp16_mv":
                pct = f"{100 * r['gbps'] / roof:.1f}%" if roof else "-"
                print(f"| `{r['kernel']}` | {r['format']} | {r['ms_median']:.4f} | "
                      f"{r['gbps']:.1f} | {pct} |")
        for k in ("q8_v5_soa_smem", "q4_v5_soa_smem"):
            if k in lad:
                r = lad[k]
                print(f"| `{k}` (CUDA) | {LABEL[k][0]} | {r['ms_median']:.4f} | "
                      f"{r['gbps']:.1f} | {100 * r['gbps'] / roof:.1f}% |")
        print()

    # energy
    ep = RES / "energy_rtx3050.json"
    if ep.exists():
        e = json.loads(ep.read_text(encoding="utf-8"))
        print("## 5. Energy\n")
        print(f"Method: `{e['method']}`. Idle draw measured at "
              f"{e['idle_pre']['watts']:.3f} W before the sweep and "
              f"{e['idle_post']['watts']:.3f} W after; the spread between those two "
              f"is the uncertainty on every above-idle figure below.\n")
        print("| kernel | mean W | mJ per call | pJ per weight byte |")
        print("|---|---|---|---|")
        for r in e["runs"]:
            print(f"| `{r['kernel']}` | {r['watts_window']:.2f} | "
                  f"{r['joules_per_iter'] * 1e3:.3f} | {r['pJ_per_weight_byte']:.0f} |")
        runs = {r["kernel"]: r for r in e["runs"]}
        if "q8_v0_naive" in runs and "q8_v5_soa_smem" in runs:
            a, b = runs["q8_v0_naive"], runs["q8_v5_soa_smem"]
            print(f"\nFrom the naive kernel to the best one, mean power rose from "
                  f"{a['watts_window']:.1f} W to {b['watts_window']:.1f} W while energy "
                  f"per call fell {a['joules_per_iter'] / b['joules_per_iter']:.2f}x. "
                  f"The faster kernel draws more and costs less, which is the whole "
                  f"argument for racing to idle.\n")
        if "q8_v5_soa_smem" in runs and "q4_v5_soa_smem" in runs:
            a, b = runs["q8_v5_soa_smem"], runs["q4_v5_soa_smem"]
            print(f"q4_0 costs {b['joules_per_iter'] / a['joules_per_iter']:.2f}x the "
                  f"energy per call of q8_0 and "
                  f"{b['pJ_per_weight_byte'] / a['pJ_per_weight_byte']:.2f}x the energy "
                  f"per byte moved. The format that reads fewer bytes is the more "
                  f"expensive one on both axes.\n")


if __name__ == "__main__":
    main()
